/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmu_swordbearer_audio_Speex */

#ifndef _Included_xmu_swordbearer_audio
#define _Included_xmu_swordbearer_audio
#ifdef __cplusplus
extern "C" {
#endif
#undef xmu_swordbearer_audio_DEFAULT_COMPRESSION
#define xmu_swordbearer_audio_DEFAULT_COMPRESSION 8L
/*
 * Class:     xmu_swordbearer_audio
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xmu_swordbearer_audio_open
  (JNIEnv *, jclass, jint);

/*
 * Class:     xmu_swordbearer_audio
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xmu_swordbearer_audio_getFrameSize
  (JNIEnv *, jclass);

/*
 * Class:     xmu_swordbearer_audio
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_xmu_swordbearer_audio_decode
  (JNIEnv *, jclass, jbyteArray, jshortArray, jint);

/*
 * Class:     xmu_swordbearer_audio
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_xmu_swordbearer_audio_encode
  (JNIEnv *, jclass, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     xmu_swordbearer_audio
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmu_swordbearer_audio_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
